### ISSUE TITLE
Rails

### ISSUE THREAD

**Issue by nvielva** [IIC2143-2018-1/project#1]
Comencé el tutorial de rails que nos habían recomendado la semana pasada sin el uso de docker. En el cual llegue al capitulo 3, sin embargo, en la ayudantía de ayer quede bien confundido con el uso de rails.. Lo anterior debido a que en casi todos los comandos de rails en la ayudantía usaron docker-compose antes del código en rails. Siguiendo esta línea, ¿Como enfrento el tutorial? ¿Es lo que más me conviene para aprender bien rails? ¿ docker compose se va a tener que usar antes de todos los comandos de rails?.. Agradeceria algo de ayuda

**Comment by haroldmuller** [comment]
Hola, no te afectará en nada que los tutoriales estén sin Docker, debido a que los comandos son los mismos, solamente le antepones `docker-compose run web` para que los corra dentro del container, pero los comandos de Rails se mantienen igual como si estuvieras desarrollando sin Docker.
Te recomiendo que busques un tutorial que haga una app básica en Rails y la puedes desarrollar en un contenedor nuevo, así te vas acostumbrando tanto a Docker como a Rails. Por último, si, todos los comandos de Rails deberán ser ejecutados junto el comando de Docker.

**Comment by rasaffie** [comment]
Complementando la respuesta de Harold, por ejemplo, en el comando:
```
docker-compose run web rails db:migrate
``` 
la componente `docker-compose run web` especifica que a través de `docker-compose` se debe correr (`run`) un contenedor de la imagen `web`, para luego ejecutar el comando `rails db:migrate` en ese ambiente. Por otra parte, en el archivo `docker-compose.yml` se especifica qué es necesario para montar el contenedor `web`.
