### ISSUE TITLE
Problemas con Aplicación Rails en Docker. Pto 7 ayudantía 1.

### ISSUE THREAD

**Issue by jerosalazar** [IIC2143-2018-1/project#10]
Siguiendo las instrucciones de la ayudantía 1 estoy creando el ambiente de desarrollo en docker. Seguí todos los pasos como salen en la ayudantía, hasta que llegué al punto 7. Agregué tal como están las lineas al `config/database.yml`. El punto c me funciona, pero la creación de base de datos me tira errores como:
<img width="422" alt="captura de pantalla 2018-03-23 a las 4 40 01 p m" src="https://user-images.githubusercontent.com/30667977/37850127-e1a56f42-2eb8-11e8-92e8-3040710a2e6b.png">
Y al tratar de instalar lo que me pide sigo teniendo error tras error.
¿Alguna idea de que hacer?

**Comment by rasaffie** [comment]
¿Ejecutaste el comando `docker-compose build`? 

El error dice que una de las dependencias definidas en el `Gemfile.lock` no está instalada. Los comandos de `rake` no se ejecutan a menos que todas las dependencias de gemas estén satisfechas.

Si ejecutas `docker-compose run web bundle install` las gemas se instalarán en el contenedor solamente (que no guarda estados entre ejecuciones). Por esta razón debes ejecutar `docker-compose build` que hace los cambios en la imagen misma.

Si ejecutas `bundle install` directamente estás instalando las dependencias en tu máquina, y no en la imagen de docker.

**Comment by rasaffie** [comment]
@jerosalazar Sube tu proyecto al repositorio de tu grupo para ver si hay errores de configuración.
