### ISSUE TITLE
Problema con el paso 9 de la ayudantia (crear el controlador)

### ISSUE THREAD

**Issue by nvielva** [IIC2143-2018-1/project#11]
Todo se ejecuta bien, sin embargo, tengo el problema de que al correr el comando:

docker-compose exec web rails generate controller welcome

No se crea el archivo app/views/welcome/index.html.erb que la ayudantía espera que se cree.

Estos archivos se estan creando con el comando:
<img width="657" alt="captura de pantalla 2018-03-26 a la s 15 52 44" src="https://user-images.githubusercontent.com/20866413/37926480-d4cb8732-310d-11e8-9394-803ca6e6341b.png">

Mi duda es si tendre algun problema en la instalación.. Nose porque se puede estar generando este problema..

**Comment by rasaffie** [comment]
Hola, para generar la vista deberías haber ejecutado el comando con `index` al final:
```
docker-compose run web rails generate controller welcome index
```
De esta forma se te crearía un controlador con la acción `index` definida y la vista asociada. Por como ejecutaste el comando se te debe haber creado un controlador sin ningún método definido.

Más información [aquí](http://guides.rubyonrails.org/command_line.html#rails-generate).

**Comment by nvielva** [comment]
perfecto! si me di cuenta recién.. muchas gracias por la rapidez de la respuesta.. quizás podrían modificar la ayudantia para que no se genere confusión..
Saludos!

**Comment by nvielva** [comment]
Un detalle.. para ejecutar todos estos comandos tiene que estar corriendo la app? a esto me refiero de que previamente si o si tiene que haberse ejecutado docker-compose up?

**Comment by rasaffie** [comment]
No, `docker-compose up` levanta el servidor para permitir solicitudes al `localhost`. Estos otros comandos son herramientas del _framework_ para facilitar el desarrollo (sino habría que crear los archivos manualmente).

**Comment by jerosalazar** [comment]
Hola, me pasa que trato de hacer este mismo paso y me dice que no puede encontrar nokogiri (`Could not find nokogiri-1.8.2 in any of the sources`) y que debo instalarlo antes de seguir. Si trato de hacer `docker-compose run web bundle install` no me instala esto, alguna idea de que puedo hacer?

**Comment by rasaffie** [comment]
Revisa el _issue_ https://github.com/IIC2143-2018-1/project/issues/10 y avisa si ese era el problema.

**Comment by jerosalazar** [comment]
Hice justamente lo que dice la issue 10 y no me funciona, no se si deba agregar el nokogiri al Gemfile o algo así
