### ISSUE TITLE
localhost no funciona en Docker Toolbox

### ISSUE THREAD

**Issue by Snorlax8** [IIC2143-2018-1/project#12]
Hola!

Seguí todos los pasos de la ayudantía 1, todos los archivos y la base de datos del último paso fueron creados correctamente, pero aún así no me carga la página de "You're on rails". Algo que se me ocurre que puede tener que ver, es que al momento de hacer docker-compose up, parte del mensaje entregado dice lo siguiente:

![1](https://user-images.githubusercontent.com/14048037/37931448-02420e62-311c-11e8-96ba-fb5ecfee271d.png)

Aparece que el servidor se detiene, aunque de todas formas después dice que está todo listo para aceptar conexiones. ¿Alguien sabe qué pasa?

Muchas gracias!

**PS: Estoy trabajando en Windows 10 con Docker Toolbox.**

**Comment by jerosalazar** [comment]
A mi me pasó algo parecido. Me funcionó la primera vez, pero de ahí en adelante cuando hacía `docker-compose up` me decía que ya había un server funcionando. Encontré esto y me solucionó todo:
https://stackoverflow.com/questions/35022428/rails-server-is-still-running-in-a-new-opened-docker-container
El problema era que cerré una vez el terminal de donde estaba trabajando sin hacer `docker-compose down` entonces un archivo quedo abierto diciendo que el server aun no se cerraba o algo por el estilo.

**Comment by Snorlax8** [comment]
Gracias por comentar, Jerónimo! Pero creo que tu problema era diferente a lo que me sucede a mí. A ti te logró salir una vez, a mí nunca me ha podido cargar la página. `docker-compose down` efectivamente me sirve para poder hacer `docker-compose up` otra vez desde cero, pero me sigue saliendo el mismo resultado que publiqué.

**Comment by rasaffie** [comment]
¿Al resto de tu equipo les funciona la configuración de docker para su aplicación?

**Comment by Zepk** [comment]
@rasaffie No estoy seguro de haber entendido su pregunta, pero asumo que está preguntando si pudimos seguir la guía de la ayudantia y lograr hacer que funcione.

De ser así, de momento soy el único en el grupo que ha logrado hacerlo funcionar (yo y @Snorlax8  seguimos exactamente los mismos pasos), sin embargo a ella no le funciona y a mi si, la única diferencia es que yo tengo windows 10 Pro, y ella tiene windows 10 home, por tanto tenemos instalaciones de Docker diferentes.

Tema a parte, a mi me salia la pantalla de bienvenida "you are on rails" al ingresar a localhost incluso sin haber creado la base de datos en el paso 7.d de la ayudantia, cosa que hasta donde entiendo no debiese ser posible. Pero haciendo todo otra vez, logré hacer que todo funcionara como debe.

**Comment by Snorlax8** [comment]
Actualización muy tardía, por si a alguien le sirve: después de muchos intentos, me rendí con Docker Toolbox y me cambié a Windows 10 Pro con la licencia que entrega la U. Con esto, pude descargar Docker for Windows y el problema desapareció.

**Comment by andresfdezc** [comment]
Para futura referencia, `localhost` no funciona en Docker Toolbox y hay que usar `192.168.99.100` en cambio.

Fuente: https://stackoverflow.com/questions/42866013/docker-toolbox-localhost-not-working
