### ISSUE TITLE
Repositorio heroku dentro del de Github

### ISSUE THREAD

**Issue by movaldivia** [IIC2143-2018-1/project#13]
Hola!

Sin querer puse el repositorio de heroku dentro de la carpeta del repositorio de GitHub(web), lo quiero eliminar para separar la parte de desarrollo y producción. Según lo que busqué, para eliminarlo necesito ser admin del repositorio.  

![duda](https://user-images.githubusercontent.com/24725124/37936028-56770132-312a-11e8-890a-4e1d529a3877.png)

Ayuda! y gracias de antemano

**Comment by andresfdezc** [comment]
Por favor revisa si este mismo error se encuentra en tu rama `master`. En este momento estás mirando la rama `a8037a8c0` que es de las que Git crea cuando hay conflictos. Si tu rama master se ve normal y sin la carpeta `appingsoftware`, podrás continuar sin el mismo problema. Más adelante aprenderemos a manejar las ramas.

Necesito aclararte que el ambiente de desarrollo y producción no son repositorios distintos. Son la configuración de máquinas distintas donde se ejecuta el mismo código: tu computador y el servidor en Heroku. Para Heroku, se espera que agreguen el repositorio remoto de éste al repositorio local de Git con el que estén trabajando, o que conecten su aplicación a la rama master del repositorio que les dimos.

**Comment by andresfdezc** [comment]
Acabo de eliminar esa carpeta de su repositorio.
