### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by movaldivia** [IIC2143-2018-1/project#14]
Por ejemplo, para el CRUD de usuario
Dado,
1) Como usuario quiero registrarme para acceder a mayores beneficios
2) Como usuario quiero eliminar mi cuenta para que mis datos no queden el el foro

¿Qué sería más correcto?
1 y 2 "separados"
1 y 2 "juntos"

Mi duda es más que nada porque en clase hablamos que las historias debían hacerse más o menos en un día full time. Y las dos funcionalidades creo que se hacen juntas en menos de un día, pero son funcionalidades muy diferentes. Por lo que no sé si las debería agrupar en un story como "acciones de usuario" o no.

**Comment by rasaffie** [comment]
Lo principal que define una historia de usuario es el usuario, el objetivo y el beneficio. Si alguno de estos elementos es muy distinto entre 2 historias, entonces deben ser historias separadas (independiente del esfuerzo para realizarlas).

La medida de que "el esfuerzo para desarrollar una historia no sea más de un día de trabajo" sirve para evaluar si una historia es muy genérica y podría ser dividida en otras historias con mayor detalle.
