### ISSUE TITLE
Warning en paso 7.c

### ISSUE THREAD

**Issue by acrojas2** [IIC2143-2018-1/project#15]
Hola: 
Escribo porque hace días que he intentado hacer la parte de la app y no he podido porque me pasa lo siguiente:
<img width="592" alt="captura de pantalla 2018-03-27 a las 10 30 42 p m" src="https://user-images.githubusercontent.com/26121354/38003611-b1d8907e-320e-11e8-8f0e-71c7753e8a29.png">
No sé porqué pasa eso si en database.yml agrego lo que dice en el punto 7.b (aquí la prueba de que lo hago):
<img width="592" alt="captura de pantalla 2018-03-27 a las 10 30 42 p m" src="https://user-images.githubusercontent.com/26121354/38003647-e06f9bc6-320e-11e8-95ca-92cd9c25c846.png">
* He seguido todos los pasos al pié de la letra.
** Lo único que cambié fue que el directorio no lo llamo example sino que lo llamo App, pero cambié lo siguiente en dockerfile y docker-compose.yml respectivamente:
<img width="305" alt="captura de pantalla 2018-03-27 a las 10 35 46 p m" src="https://user-images.githubusercontent.com/26121354/38003729-4c7f5d2e-320f-11e8-9a76-8762455a1759.png">
<img width="329" alt="captura de pantalla 2018-03-27 a las 10 35 34 p m" src="https://user-images.githubusercontent.com/26121354/38003736-5064a69c-320f-11e8-9e18-5d7de4ac5485.png">
¿Hay algo más que deba modificar? ¿Dónde se genera el error?
Saludos!

**Comment by andresfdezc** [comment]
Lo que estás mostrando no es un error, sólo una advertencia y no debiese afectar el funcionamiento real de la aplicación. Es normal que aparezca porque en la guía que les entregamos no definimos una contraseña para la base de datos explícitamente.

**Comment by acrojas2** [comment]
@andresfdezc pero no avanza, se queda pegado ahí... (horas) ->¿Qué hago?

**Comment by andresfdezc** [comment]
¿Se imprime alguna línea después de esa advertencia?

**Comment by acrojas2** [comment]
@andresfdezc esto:
<img width="717" alt="captura de pantalla 2018-03-27 a las 10 42 04 p m" src="https://user-images.githubusercontent.com/26121354/38003920-2742aab0-3210-11e8-9a0d-fc1b32bdaf31.png">
y ahí queda...

**Comment by andresfdezc** [comment]
Por lo que se alcanza a ver, no está pegado. Simplemente está esperando a que uses la aplicación. Cuando ejecutas `docker-compose up` estás encendiendo tu aplicación y a continuación se mostrarán los logs o output de la aplicación mientras corre.

Para apagarla puedes presionar CTRL + C. Puedes continuar con el paso siguiente en otra terminal (en el mismo directorio) o repetir este paso de la siguiente forma:

`docker-compose up -d`

Esto hará que la aplicación se corra por atrás (`--detached`) y no te muestre los logs.

También puedes probar tal como estás ahora entrando a http://localhost:3000 en tu navegador para ver si está funcionando.
