### ISSUE TITLE
Problema deploy Heroku

### ISSUE THREAD

**Issue by Zepk** [IIC2143-2018-1/project#16]
Hola

El problema que presento es el siguiente, tengo la app funcionando de manera local sin problema alguno, pero luego de hacer el deploy a Heroku, utilizando Heroku CLI, sin embargo cuando intento acceder a la aplicacion en Heroku, obtengo esto:

![screenshot_1](https://user-images.githubusercontent.com/11397612/38006994-b7b79d78-321d-11e8-9097-19c4492ae97b.png)

Estos son los logs de Heroku, sin embargo no logro entender lo que dicen

![screenshot_2](https://user-images.githubusercontent.com/11397612/38007033-e285aa36-321d-11e8-85f7-832e01f4bb50.png)

Lo mas sospechoso que encontré fue este mensaje que me salio mientras hacia el deploy a Heroku, pero entiendo que no debiese tener nada que ver con el problema que estoy teniendo ahora.

![screenshot_3](https://user-images.githubusercontent.com/11397612/38007139-4e4b6396-321e-11e8-9dd6-ce914981e53c.png)

Si alguien pudiese orientarme respecto a el problema que estoy teniendo, lo agradeceria

**Comment by rasaffie** [comment]
Debe ser porque no tienes ninguna ruta especificada en el archivo `config/routes.rb`. El mensaje 'Yay! You're on Rails!' aparece solamente en el entorno de desarrollo si la ruta `root` no está definida. Sin embargo, en el ambiente de producción (en este caso Heroku), la aplicación se cae. Tienes que definir un controlador y una vista como se hizo en la ayudantía.

La segunda imagen que muestras es porque estás haciendo el _deploy_ a Heroku a través de docker. En el issue https://github.com/IIC2143-2018-1/project/issues/4 se habla de otra alternativa para subir la aplicación.

**Comment by Zepk** [comment]
Efectivamente no tenia nada en ese archivo, sin embargo ahora lo tengo tal y como sale en la ayudantia, al entrar a localhost me aparece el mensaje "Hello World" como debería, sin embargo tanto el error como los logs de Heroku se mantienen igual.

Respecto a lo del error de la segunda imagen ¿se refiere a los logs de Heroku? es decir ¿siempre que suba la app a través de Docker esto fallará? ¿o se refiere a la tercera imagen, la que me da el security warning?

**Comment by rasaffie** [comment]
Me refería a la 3º imagen, lo siento. Trata de hacer el _deploy_ como dice el _issue_ https://github.com/IIC2143-2018-1/project/issues/4, para ver si el problema es por hacer deploy con una imagen de _docker_ construida en Windows.

**Comment by Zepk** [comment]
Efectivamente, hacer el deploy de manera diferente solucionó el problema, muchas gracias
