### ISSUE TITLE
Problema en la creación de la app de rails

### ISSUE THREAD

**Issue by jerosalazar** [IIC2143-2018-1/project#17]
En el punto de crear la app de rails de "Hello World" con docker, estoy siguiendo los pasos de la ayudantía, pero al momento de correr `docker-compose exec web rails generate controller welcome` me sale el error:
<img width="513" alt="captura de pantalla 2018-03-28 a las 11 52 07 a m" src="https://user-images.githubusercontent.com/30667977/38037042-6c8326ae-327e-11e8-9a10-4822bbaa8c50.png">
Lo mismo ocurre si corro `docker-compose exec web rails generate controller welcome index`. 
Al hacer `docker-compose run web bundle install` no se me instala nada llamado nokogiri y no se que más pueda hacer para arreglarlo. ¿Alguna idea de que pueda solucionar esto? Gracias.

**Comment by rasaffie** [comment]
¿Solucionaste este problema?
