### ISSUE TITLE
Edicion de archivo Dockerfile y docker-compose

### ISSUE THREAD

**Issue by nvielva** [IIC2143-2018-1/project#18]
Hola, estoy con la duda de si es necesario o no modificar el archivo dockerfile y docker-compose, especialmente en la parte donde referencia a la carpeta EXAMPLE. Al correrlo sin cambiar este detalle la aplicación me funciona bien tanto en el localhost (Muestra Hello World) como el la app corriendo con heroku (Muestra Hello World), sin embargo, al modificar el detalle haciendo referencia al nombre de la carpeta de mi grupo no funciona en localhost (muestra Yay! You’re on Rails!) pero si en la app subida en heroku (Muestra Hello World)
<img width="1440" alt="captura de pantalla 2018-03-28 a la s 13 53 30" src="https://user-images.githubusercontent.com/20866413/38044181-6b4d27f6-328f-11e8-9fca-855892d17179.png">

**Comment by rasaffie** [comment]
Sí es necesario que modifiquen el nombre de la carpeta en ambos archivos. Ese nombre debe ser igual al de la carpeta donde estén contenidos (el cual debería ser el nombre de su repositorio).

Heroku no utiliza los archivos de Docker para montar la aplicación, por lo que es normal que no tengas problemas.

**Comment by rasaffie** [comment]
Revisando el repositorio de tu grupo veo que a la aplicación la nombraron `example`, por lo que lo más seguro es que esté dentro de una carpeta `example` también. Por esta razón fallaría si cambias los archivos de configuración de Docker.

Es buena práctica que los proyectos el mismo nombre que el repositorio de git.
