### ISSUE TITLE
Versión de Ruby no soportada por Rubocop

### ISSUE THREAD

**Issue by fnquinteros** [IIC2143-2018-1/project#19]
Hola, estoy teniendo problemas con rubocop. Abro el terminal en la carpeta donde está routes.rb y ejecuto rubocop sobre ese archivo y me pasa lo siguiente:

![screenshot from 2018-03-28 21-34-28](https://user-images.githubusercontent.com/17592014/38063504-ecd5e4ee-32cf-11e8-9c33-358ada167c88.png)
1) No entiendo el warning :sweat_smile: 
2) No sé porqué me tira ese error. 

Saludos!

**Comment by andresfdezc** [comment]
¿Puedes ver qué versión de ruby tienes instalada en tu computador con `ruby -v`?

Está reclamando porque uno puede decidir una versión de Ruby a usar en Rubocop y nosotros les configuramos la 2.5 (última estable) para su proyecto en Docker. Como Rubocop funciona afuera de Docker simplemente usa la versión que tengas en tu computador.

**Comment by fnquinteros** [comment]
tengo instalada la 2.5

**Comment by andresfdezc** [comment]
¿Y dice 2.5 al hacer `ruby -v`? Esto es importante porque uno puede tener varias versiones y se puede estar ejecutando con una anterior.

Adicionalmente, ¿me puedes mostrar que sale al correr `rubocop -V`? (notar V mayúscula)

**Comment by fnquinteros** [comment]
Efectivamente era la versión de ruby. Asumí que tenia la 2.5 porque lo instalé hace poco, pero estaba con la 2.3. Lo actualicé y se solucionó.  Al hacer rubocop -v sale 0.54.0. De todas maneras, ya está solucionado. Muchas gracias!
