### ISSUE TITLE
[.ENV]

### ISSUE THREAD

**Issue by Okhan97** [IIC2143-2018-1/project#2]
Hola, no me quedó claro de la ayudantia, ¿donde se supone que debo crear el archivo .env ?
Y le debo poner cualquier nombre al archivo .env y dejarlo en blanco ??

Basicamente estoy perdido en que hacer justo despues de instalar docker D:

**Comment by haroldmuller** [comment]
Hola, el archivo .env lo debes crear en el root de tu aplicación, es decir, donde en están los archivos Gemfile, Dockerfile, etc. El nombre debe ser necesariamente .env y si lo dejas en blanco.
Despues de instalar Docker lo que deberias hacer es generar tu primer container y generar el código base de tu app Rails. Para eso te recomiendo seguir la documentación de Docker de como crear una ap en Rails junto con Docker, te dejo el link al final. 

[Quickstart: Compose and Rails](https://docs.docker.com/compose/rails/)

**Comment by Okhan97** [comment]
Documento de texto ?

**Comment by haroldmuller** [comment]
Para crear el archivo .env, puedes hacerlo desde consola escribiendo el comando `touch .env`. Con eso debería crearse el archivo en la carpeta donde estés parado

**Comment by Okhan97** [comment]
Ya me salió, gracias por la ayuda.
Algo que vale la pena decir: No me funcionó ni con el windows powershell ni con la consola (me refiero al comando touch), pero cuando lo hice con la consola de "GUI Bash" si funcionó.

¿Alguna idea de por que esto ocurre?

**Comment by haroldmuller** [comment]
Perdón, touch es un comando de Unix (macOS o Linux), para Windows existe un equivalente, dejo link con equivalentes.

[Windows equivalent of 'touch' (i.e. the node.js way to create an index.html)](https://stackoverflow.com/questions/30011267/windows-equivalent-of-touch-i-e-the-node-js-way-to-create-an-index-html)
