### ISSUE TITLE
Docker y Gemas

### ISSUE THREAD

**Issue by nvielva** [IIC2143-2018-1/project#20]
Hola, estoy tratando de aprender de rails con tutoriales, sin embargo, estoy teniendo muchos problemas con la instalación de gemas.. Aparentemente no las guarda en la imagen de docker, de esto me di cuenta porque si le pido una lista de las gemas instaladas usando el comando **docker-compose run web gem query** (una vez aplicado el bundle install el cual uso de esta forma: **docker-compose run web bundle install** ) y no aparecen las que quería instalar dentro de este.. 
Saludos

**Comment by nvielva** [comment]
Podrían subir algo para entender como tenemos que instalarlas?

**Comment by rasaffie** [comment]
Mira lo que respondí en el issue https://github.com/IIC2143-2018-1/project/issues/10. Dime si te quedan dudas o necesitas que explique algo más.

**Comment by nvielva** [comment]
Buenisimo! Entonces en que casos tendriamos que aplicar docker-compose build nuevamente? solo para la instalación de gemas?

**Comment by nvielva** [comment]
Buenisimo! Entonces en que casos tendriamos que aplicar docker-compose build nuevamente? solo para la instalación de gemas? @rasaffie

**Comment by rasaffie** [comment]
Si cambian el `Gemfile` deberán construir la imagen nuevamente. También tendrán que hacerlo si modifican el `Dockerfile`.

**Comment by rasaffie** [comment]
Por otra parte, si cambian las gemas del proyecto deberán ejecutar `docker-compose build` y luego `docker-compose run web bundle install`, para que así el `Gemfile.lock` refleje los cambios. Si no ejecutan estos 2 comandos el `Gemfile` no coincidirá con el `Gemfile.lock`, y por esta razón Heroku no les permitirá subir su aplicación.
