### ISSUE TITLE
Problemas para subir app a Heroku

### ISSUE THREAD

**Issue by jerosalazar** [IIC2143-2018-1/project#22]
Hola, he estado intentando un buen rato subir mi app a heroku, pero sigo teniendo problemas. El mas reciente es con la base de datos. Cuando trato de realizar el paso "Migrate your Database" de esta [guía](https://devcenter.heroku.com/articles/getting-started-with-rails5), que indica como subir mi app, me sale un mensaje diciendo que se abortó la operación debido a que no se encuentra el archivo rakefile. Buscando como puedo solucionar esto, llegue a esta [página](https://stackoverflow.com/questions/18452701/ruby-on-rails-no-rakefile-found-error/26503630), pero al hacer el archivo rakefile como sale, me empezaron a salir muchos errores al hacer `git push heroku master` y no puedo hacer el push. Alguna idea de que podría estar pasando o como solucionarlo?

**Comment by haroldmuller** [comment]
Hola,
fijate en la ayudantía 1 de settings. Viendo tu repo, falta el host, username y password en el archivo `config/database.yml`.
Si los problemas persisten, prueba con lo que aparece en este [link](https://stackoverflow.com/questions/24320837/heroku-run-rake-dbmigrate-rake-aborted-no-rakefile-found). Prueba y cuenta si te funcionó o no.

Saludos,

**Comment by jerosalazar** [comment]
Gracias @haroldmuller . Cambie lo del host, pero ahora me pasa que cuando hago 'git push heroku master' me dice esto:
<img width="630" alt="captura de pantalla 2018-04-11 a las 1 47 49 p m" src="https://user-images.githubusercontent.com/30667977/38630982-d8d24158-3d8e-11e8-8537-87ba5da108e8.png">
Que puedo hacer con eso?

**Comment by rasaffie** [comment]
Mira este [link](https://devcenter.heroku.com/articles/sqlite3) y este [otro](https://stackoverflow.com/a/13083453/4354672). En resumen, Heroku no permite que las aplicaciones utilicen _sqlite3_ en ambiente de producción, por eso en el curso usamos _postgres_.

También, te recomiendo que desarrolles más tus habilidades para leer los errores en consola y buscar soluciones en _google_. Esto es una habilidad fundamental para cualquier desarrollador y necesita práctica.

**Comment by jerosalazar** [comment]
Ya quedó todo funcionando, muchas gracias!
