### ISSUE TITLE
Diagrama E/R

### ISSUE THREAD

**Issue by movaldivia** [IIC2143-2018-1/project#24]
Hola!

Cuando se realiza un diagrama E/R es necesario saber en que "pestaña" estamos?

Por ejemplo, crear un objeto "inicio de seción" aparte de la acción "inicio de sección" o crear un objeto "menu principal" donde se publica foros o bastaría con crear la "actividad" publicar

**Comment by fdoflorenzano** [comment]
Hola.
Tu ejemplo creo no fue muy claro, o muy específico a lo que estabas pensando. De todas formas, me da la impresión que estás confundiendo lo que es el diagrama E/R. Este simplemente busca mostrar el modelo de datos necesario para sus plataformas, lo cual **no** incluye acciones, estados o "pestañas" de la página.  Entonces, es solo relevante los objetos de interés, que atributos tienen, y como se relacionan entre ellos, independiente de si hay que hacer una acción para crearse o no. Piensa que esto también se relaciona fuertemente con la base de datos que tiene por detrás la plataforma. Esto te ayudaría a modelar y construir sus tablas en un modelo entidad-relación.

**Comment by movaldivia** [comment]
@fdoflorenzano 
Ya me quedó claro respecto a lo de las "pestañas"
Ahora me surgió otra duda si yo quiero que un usuario "visita", al logearse o registrarse, se convierta en usuario común, habría una relación "login o registrarse" o no es necesario especificar esto?

**Comment by fdoflorenzano** [comment]
Eso es más una interacción o acción que ocurre en la plataforma, lo cual no le interesa al nivel de modelo de datos al no tratarse de una vinculación que caracterice a los usuarios.
