### ISSUE TITLE
PG::ConnectionBad

### ISSUE THREAD

**Issue by movaldivia** [IIC2143-2018-1/project#25]
Hola estoy siguiendo esta guia http://guides.rubyonrails.org/getting_started.html (5.4) para hacer un modelo

Tras realizar este comando 
`$ bin/rails generate model Article title:string text:text`

tendría que poder hacer 
`$ bin/rails db:migrate`

Pero me tira el siguiente error:
```
rails aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
```
No sé si alguien sabe como solucionarlo. O por donde le tinca que es el error

**Comment by andresfdezc** [comment]
El error que te aparece es porque no tienes una base de datos sobre la cual correr esas migraciones.

Como vimos en la ayudantía de ayer, tienes que ejecutar dichos comandos dentro de tu contenedor de Docker anteponiendo `docker-compose exec <NOMBRE_DE_LA_IMAGEN>` al comando que quieras ejecutar, para que esté la base de datos del contendor `postgres` que creamos antes en el semestre.

Si has trabajado en el proyecto como hemos sugerido, el primer comando que estás intentando usar deberías escribirlo de la siguiente forma, después de haber encendido los contenedores con `docker-compose up`:

```
docker-compose exec web rails generate model Article title:string text:text
```

Y luego, de la misma forma:

```
docker-compose exec web rails db:migrate
```

También, si se te olvidó crear las bases de datos al crear la aplicación, puedes correr:

```
docker-compose exec web rails db:create
```
Si no estás usando Docker, necesitas encender Postgres primero y revisar que tu aplicación esté conectada a la base de datos que quieras usar.

**Comment by movaldivia** [comment]
No me funciona usar los comandos que me dices. Si tengo esto debería funcionar?

![sqll](https://user-images.githubusercontent.com/24725124/38771239-e60fb166-3ff5-11e8-89d5-3fa234c433f2.PNG)

O debería intentar instalar todo denuevo?

**Comment by andresfdezc** [comment]
Si tienes los contenedores corriendo como muestras, los comandos te debiesen funcionar. En particular, debieses correr `db:create` y luego `db:migrate`.

Puede ser que te hayas saltado el paso de agregar la configuración de la base de datos al archivo `config/database.yml`. Por favor revisa el paso 7 de la ayudantía 1.

**Comment by movaldivia** [comment]
Si tenías razón no había configurado bien el `config/database.yml`
Me funciona ahora !
Me quede con una duda igual, porque la imagen se llama `postgres`, y no `soft_postgres_1` (teniendo en cuenta la imagen del comentario anterior)
Gracias !

**Comment by andresfdezc** [comment]
`postgres` es el nombre de la imagen que especificamos en `docker-compose.yml` y `soft_postgres_1` es el nombre de tu contenedor en particular. Ese archivo define imágenes, que deben servir para varios contenedores con la misma estructura, por lo que poner `postgres` es más general y reutilizable.
