### ISSUE TITLE
Diferencias entre exec y run

### ISSUE THREAD

**Issue by nvielva** [IIC2143-2018-1/project#26]
Con estos comandos me refiero a docker-compose run web y docker-compose exec web
Cuales son las diferencias entre estos para ejecutar los comandos de docker? y en que casos tenemos que usar uno en lugar del otro? 
Saludos!

**Comment by andresfdezc** [comment]
`exec` sirve para correr un comando en un contenedor que ya esté andando y `run` para crear un nuevo contenedor a partir de una imagen y correr ese comando allí dentro.

Si ya creaste tus contenedores con `docker-compose up -d`, puedes correr todo lo que necesites con `exec`.

Fuentes:
https://docs.docker.com/engine/reference/commandline/exec/
https://docs.docker.com/compose/reference/exec/
https://docs.docker.com/engine/reference/commandline/run/
https://docs.docker.com/compose/reference/run/

**Comment by nvielva** [comment]
Ok perfecto, agradecido.. y el -d en el docker-compose up que hace en docker? lo deja como corriendo?

**Comment by andresfdezc** [comment]
Sí, lo deja corriendo por atrás. `-d` es equivalente a `--detach`.

Puedes revisar más opciones en https://docs.docker.com/compose/reference/up/.

**Comment by nvielva** [comment]
Comento porque estaba teniendo el problema de que la app no me reconoce la base de datos si hago docker-compose down y despues docker-compose up de nuevo.. pq podria pasarme? @andresfdezc

**Comment by andresfdezc** [comment]
`docker-compose up` crea los contenedores nuevos desde cero. Uno puede apagarlos con `docker-compose stop` y reiniciarlos con `docker-compose start`. `docker-compose down` eliminará los contenedores y borrará la base de datos. Por lo tanto, necesitarás crear de nuevo las bases con `docker-compose exec web rails db:create` si vuelves a hacer `up`.

**Comment by nvielva** [comment]
Buenisimo! gracias Andrés!

**Comment by mraddatz** [comment]
Entonces cuando dejemos de trabajar en el proyecto para luego comenzar denuevo que comando recomiendas usar para cerrar docker?

**Comment by andresfdezc** [comment]
Siempre revisen el estado de sus contenedores con

```
docker-compose ps
```

Si no existen, créenlos con

```
docker-compose up --detach
```

Si existen y su *status* es distinto de *up*, enciéndanlos con

```
docker-compose start
```

Los *logs* de sus contenedores los podrán ver con

```
docker-compose logs --follow
```

Y finalmente, pueden apagarlos con

```
docker-compose stop
```

Si quieren destruirlos para siempre:

```
docker-compose down
```

PS: @mraddatz Perdón por la demora en responder.
PS2: Recomiendo ojear [la referencia de Docker Compose](https://docs.docker.com/compose/reference/).
