### ISSUE TITLE
Creacion controladores con docker

### ISSUE THREAD

**Issue by mraddatz** [IIC2143-2018-1/project#27]
Si creo nuevos controladores es necesario hacerlo con el "docker-compose run web rails generate controller .. " o puedo hacerlos simplemente como new files (sin invocar a docker-compose)?

**Comment by rasaffie** [comment]
El comando `generate` de _Rails_ sirve para facilitar el desarrollo: crea todos los archivos asociados al generador que se invoca. De todas formas, siempre puedes crear los archivos manualmente y completar con el código necesario.

La respuesta anterior es independiente del uso _docker_.
