### ISSUE TITLE
[Rake aborted!]

### ISSUE THREAD

**Issue by Okhan97** [IIC2143-2018-1/project#3]
![image](https://user-images.githubusercontent.com/26289334/37562475-e5c6f840-2a47-11e8-88c7-45d6627fb528.png)

Ya estoy en las ultimas, pero cuando intento el comando "docker-compose run web rake db:create" me arroja ese error. Segun la guia era solo para conectarlo con una base de datos, pero aunque me intente meter al localhost no aparece nada :/

Edit: No tengo ningun "Rakefile", se supone que debo crearlo yo ?

**Comment by haroldmuller** [comment]
Hola, con la información que me diste no puedo saber exactamente que pasó, pero revisa en la carpeta config, el archivo database.yml, en el debiste agregar el host, name y password de la base de datos. En la guía de aparece el host como db debido a que al servicio de postgres le ponen db en el archivo docker-compose.yml. En el archivo que de configuración que les entregamos en el curso aparece como postgres, por lo que en el archivo database.yml el host debería llamarse postgres. Prueba con eso.
Otra cosa, solo para que sepas el comando rake db:create sirve para crear las base de datos de los distintos ambientes, por lo que solo se debe correr al momento de setear la base de datos. Eso :)

**Comment by rasaffie** [comment]
Si no tienes el archivo `Rakefile` significa que no has inicializado el proyecto con el comando: 
```
docker-compose run web rails new . --force --database=postgresql
```
