### ISSUE TITLE
[Error docker-compose run web bin/yarn]

### ISSUE THREAD

**Issue by Okhan97** [IIC2143-2018-1/project#32]
Hola buenas, al correr:
`docker-compose run web bin/yarn`

Me arroja el siguiente error:
`/usr/bin/env: ‘ruby\r’: No such file or directory`

He googleado pero solo habian soluciones para Linux e iOS.

**Comment by andresfdezc** [comment]
A esta issue le falta contexto. ¿Qué estás intentanto hacer?
