### ISSUE TITLE
Database docker-compose build

### ISSUE THREAD

**Issue by movaldivia** [IIC2143-2018-1/project#33]
Hola como puedo hacer un "docker-compose build" sin perder los datos que ya tengo?

**Comment by rasaffie** [comment]
¿A qué datos te refieres?

**Comment by movaldivia** [comment]
Por ejemplo, si creo un modelo usuario y hago una "instancia" tras hacer "docker-compose build" se me borra

**Comment by rasaffie** [comment]
El comando `docker-compose build` no debería generar esto. Revisa si con lo que aparece en [esta issue](https://github.com/IIC2143-2018-1/project/issues/26) se resuelve tu problema.
