### ISSUE TITLE
problemas para conectarse a la db a través de local host con docker-compose en windows 10 pro

### ISSUE THREAD

**Issue by cirey1** [IIC2143-2018-1/project#34]
<img width="960" alt="2018-04-19" src="https://user-images.githubusercontent.com/30696119/38997929-ebfaefe6-43c4-11e8-80b1-bede629992d5.png">

**Comment by rasaffie** [comment]
Esto no es una _issue_ válida: revisa el procedimiento descrito [aquí](https://github.com/IIC2143-2018-1/project#procedimiento), en especial donde dice: 

> Escribe una entrada **explicando bien el problema o pregunta**
