### ISSUE TITLE
[Error run web rake db:setup]

### ISSUE THREAD

**Issue by Okhan97** [IIC2143-2018-1/project#35]
Hola buenas,

Cuando intento ejecutar el comando `docker-compose run web rake db:setup` me sale el siguiente error:
![image](https://user-images.githubusercontent.com/26289334/39003592-8c3cb03c-43d1-11e8-9cbd-e620c2e4b111.png)

He intentado correr `docker-compose run web bundle install` y este efectivamente me instala 81 gemas, pero cuando intendo  volver a correr rake db:setup me sigue arrojando el mismo error. Pensé que se solucionaria si instalaba la gema "a mano":
![image](https://user-images.githubusercontent.com/26289334/39003759-ec9927e4-43d1-11e8-9486-b91b1e7a4a88.png)
Pero así y todo me sigue arrojando el mismo error, necesito ayuda para solucionarlo 😭

**Comment by rasaffie** [comment]
Mira https://github.com/IIC2143-2018-1/project/issues/10 y https://github.com/IIC2143-2018-1/project/issues/20
