### ISSUE TITLE
Cómo pasar variables de un controlador a un css

### ISSUE THREAD

**Issue by ouhenio** [IIC2143-2018-1/project#36]
¡Hola! ¿Existe la opción de "embedear" el valor de una variable de un controlador al css, tal como se puede hacer con los html?

Intenté agregar la extensión .erb a los archivos .scss y usar la sintaxis `<%=  @my_variable %>`, como vi por ahí en internet, pero no funciona.

**Comment by rasaffie** [comment]
No se puede hacer de esa forma.

Los _assets_ son archivos estáticos de imágenes, _CSS_ y _JS_. A diferencia del _HTML_, estos archivos se generan una sola vez al montar la aplicación en producción (ver más detalle en la documentación del [_asset pipeline_](http://guides.rubyonrails.org/asset_pipeline.html)).

No sé qué buscas hacer pero existen otras alternativas para modificar el estilo del _HTML_ dinámicamente. En [este enlace](https://stackoverflow.com/a/13944275) puedes ver algunos ejemplos.

**Comment by rasaffie** [comment]
Veo que el ejemplo que te compartí no muestra la forma que más me gusta a mí.

En los archivos _.css_ puedes definir clases, que aplicarán ciertos estilos a los elementos _HTML_ que tengan esas clases. Luego, en el archivo _.html.erb_ puedes evaluar si quieres aplicar ese estilo a un elemento dinámicamente. 

Por ejemplo, en un archivo _.css_ podrías definir las clases:
```
.red {
  color: red;
}

.blue {
  color: blue;
}
```

Luego, en el archivo _.html.erb_ podrías tener un elemento:
```
<div class="<%= @my_variable ? 'red' : 'blue' %>">
  ¿red or blue?
</div>
```

De esta forma, dependiendo del valor de `@my_variable` qué estilos se aplicarían al `div`.

**Comment by ouhenio** [comment]
Buenísima! Gracias!
