### ISSUE TITLE
[Plazo de entrega]

### ISSUE THREAD

**Issue by Okhan97** [IIC2143-2018-1/project#37]
Hola,

¿podrían dar 24 hrs mas para esta entrega?

**Comment by rasaffie** [comment]
No se extenderá el plazo de la entrega (y menos si se solicita el día anterior). Factores importantes que se buscan evaluar con el proyecto son:

* su capacidad para comprometerse con funcionalidades e hitos
* planificar el desarrollo para lograr las metas 
* evaluar y anteponerse a los riesgos del desarrollo
