### ISSUE TITLE
Localhost:3000

### ISSUE THREAD

**Issue by domingo-valdes** [IIC2143-2018-1/project#38]
Hola, tenemos el siguiente problema. Al hacer pull de nuestro repositorio, luego un docker-compose build y finalmente un docker-compose up no hay errores en el terminal. Sin embargo, cuando vamos a localhost:3000 nos dice "this site cannot be reached", no como los clasicos errores internos de la app que salen en rojo, sino como que el browser no tuviera nada que desplegar. Alguna idea?

**Comment by rasaffie** [comment]
Revisa si lo que aparece en [esta issue](https://github.com/IIC2143-2018-1/project/issues/12) soluciona el error o el problema es otro.
