### ISSUE TITLE
Miembros repositorio

### ISSUE THREAD

**Issue by movaldivia** [IIC2143-2018-1/project#39]
Hola utilice un comando de git, de mala manera, y eliminé a mis dos compañeros del repositorio. Como no soy admin no lo puedo agregar. Me pueden ayudar?

Gracias de antemano.

**Comment by fdoflorenzano** [comment]
Hola, ¿a qué te refieres con eliminar a tus compañeros del repositorio? ¿Qué comando usaste?
Todos siguen siendo parte de la mismo _team_ que tiene acceso al repositorio.

**Comment by movaldivia** [comment]
Como se ve en la imágen soy el único contribuidor. Usé un comando de git para "resetear el repo" porque teníamos unos archivos malos.

![capture](https://user-images.githubusercontent.com/24725124/39083813-753b3e28-4541-11e8-8233-c35b92eeab08.PNG)

**Comment by fdoflorenzano** [comment]
¿Qué comando? 
Ese número solo muestra el número de usuario que han realizado _commits_ en el repositorio. Pueden tener acceso y no ser contados en ese número. Yo por ejemplo, tengo acceso pero no he realizado _commits_.
¿Te refieres a que borraste _commits_ de tus compañeros? ¿O que no tienen acceso?

**Comment by movaldivia** [comment]
Desde que usé ese comando, no tienen acceso, por lo que no pueden pushear según me comentan

**Comment by fdoflorenzano** [comment]
¿Qué comando?

**Comment by movaldivia** [comment]
No lo encuentro, y tampoco me acuerdo. Pero si puedes confirmar que tienen acceso esperaría un rato para preguntarles de forma más directa el error.

**Comment by fdoflorenzano** [comment]
Como te dije, todos siguen siendo parte del mismo _team_ de _GitHub_ y tienen permisos de escritura en el repositorio.

**Comment by movaldivia** [comment]
Ya solucionamos el problema gracias !
