### ISSUE TITLE
Deploy Heroku

### ISSUE THREAD

**Issue by Hernan4444** [IIC2143-2018-1/project#4]
Hola,
 Durante la ayudantía se nos mostró como hacer el _deploy_ en Heroku utilizando Github como _Deployment method_. ¿Para este proyecto se espera que utilicemos nuestro repositorio privado del grupo para realizar el _deploy_? Que en ese caso, Heroku indica que todavía no hay permisos para acceder a los repositorios.

En base a que faltan permisos, quería confirmar si tenemos que esperar a que den los permisos correspondiente o nosotros (como grupo) nos encargamos de ver como hacer el _deploy_ mediante otros medios.

Gracias de antemano.

**Comment by rasaffie** [comment]
No podrán hacer _deploy_ en Heroku a través de Github porque es necesario que un usuario con permisos de _admin_ sobre el repositorio haga la integración (como se especifica [aquí](https://devcenter.heroku.com/articles/github-integration)).

Tendrán que hacer _deploy_ de sus aplicaciones con la segunda alternativa que se dijo en la ayudantía, que se explica en más detalle [aquí](https://devcenter.heroku.com/articles/git).

Si un grupo **realmente necesita** hacer la integración de Heroku y Github tendrá que canalizar la solicitud a través de su ayudante asignado.
