### ISSUE TITLE
PG::ConnectionBad – Could not connect to server: Connection refused

### ISSUE THREAD

**Issue by ranieto** [IIC2143-2018-1/project#40]
Después de hacer git pull para obtener los cambios realizados por un compañero (que se encargó de los CRUDs), me aparece este error al intentar entrar por localhost:3000

https://i.imgur.com/FEh5HHj.png

En el título dice "Action Controller: Exception caught".
Al correr los comandos de db:create y db:migrate me arroja los errores que se mostraron en #34 

¿Cuál podrá ser el problema? A nuestro tercer compañero tampoco le funciona. Pero al que hizo los cambios le funciona todo bien, incluso subió los cambios a heroku y la aplicación corre sin problemas.

**Comment by rasaffie** [comment]
Lo más probable es que se deba al cambio que hizo tu compañero en el archivo `database.yml` en el commit https://github.com/IIC2143-2018-1/grupo-24/commit/4d00ea3f4a7261da4ba90cd595ffb9d5e6aeba0e.

Cuando pasan errores del estilo "_antes funcionaba y ahora no_" la mejor forma de encontrar el problema es hacer `git checkout` entre _commits_ o _tags_, hasta encontrar el último estado en que la aplicación funcionaba. De esta forma se pueden ver todos los cambios realizados al código cuando dejó de funcionar la aplicación.

También, como el error hace referencia a PG, el primer lugar donde se debe buscar es en los archivos relacionados a la base de datos.

**Comment by ranieto** [comment]
Efectivamente ahí estaba el problema.
Gracias!
