### ISSUE TITLE
Error al correr migraciones 

### ISSUE THREAD

**Issue by tanavarrete** [IIC2143-2018-1/project#42]
Al correr el comando docker-compose run web rake:migrate me sale el siguiente error:
Starting grupo25_postgres_1 ... done
Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"rake:migrate\": executable file not found in $PATH": unknown

Mis compañeros trabajan con linux, puede ser por eso ?, que puedo hacer para solucionarlo?
Gracias!

**Comment by andresfdezc** [comment]
Hola! Tu comando está mal escrito. Intenta con `docker-compose run web rake db:migrate`.
