### ISSUE TITLE
Mostrar/Ocultar Fields con una checkBox

### ISSUE THREAD

**Issue by JoseValencia125** [IIC2143-2018-1/project#43]
¿Como puedo hacer para mostrar/ocultar fields al clickear una checkBox?

**Comment by andresfdezc** [comment]
Puedes buscar cómo usar Javascript en un proyecto de Rails. En particular, puedes buscar y aprender sobre cómo hacerlo con JQuery.

**Comment by rasaffie** [comment]
En la ayudantía de esta semana se conversará sobre estos temas.
