### ISSUE TITLE
Error Deploy Heroku

### ISSUE THREAD

**Issue by Zepk** [IIC2143-2018-1/project#44]
Al intentar hacer _deploy_ de nuestra aplicación, nos encontramos con el siguiente error:
![problema](https://user-images.githubusercontent.com/11397612/39833544-b783de80-53a0-11e8-8b8d-0191941b3c54.jpeg)

Aparece que se eliminó del Gemfile _rspec-rails_, lo nos parece extraño, porque nunca hemos usado eso antes. De todas formas, intentamos agregar la gema, pero eso nos entregó el siguiente error al hacer _deploy_:
![prob](https://user-images.githubusercontent.com/11397612/39834185-8d985c34-53a2-11e8-924f-44400a8aa0ab.png)

Al respecto, encontramos [este](https://stackoverflow.com/questions/36394297/heroku-push-error-could-not-detect-rake-tasks) (y varios similares) post en el que recomendaban usar un comando que solucionaba el problema. Sin embargo, si intentamos correr ese comando, la consola entrega "Cannot run one-off process at this time. Please try again later.". Para este problema no logramos encontrar solución. 

Nos gustaría saber si a alguien le pasó algo parecido alguna vez o si sabe qué podría estar sucediendo. Muchas gracias.

**Comment by andresfdezc** [comment]
Por lo que puedo ver del link que compartieron, éste les pide correr ese comando para precompilar assets en su ambiente local (su computador) y no en Heroku. Intenten corriendo eso dentro de su contenedor de Docker.

**Comment by rasaffie** [comment]
El problema es que las especificaciones de su `Gemfile` no coinciden con las de su `Gemfile.lock`. Esto es porque agregaron la gema `rspec-rails` al `Gemfile`, pero no corrieron `bundle install` para modificar el `Gemfile.lock` (o no subieron ese cambio).

Como dice el error:

> You are trying to install in deployment mode after changing your Gemfile. Run `bundle install` elsewhere and add the updated Gemfile.lock to version control. 

Por último, no agreguen los _assets_ precompilados a su versionamiento del proyecto en el repositorio. Esto solamente hará ruido al desarrollo, ya que es útil en ambiente de producción y se generan con cada _deploy_ (_Heroku_ se encarga de esto).

**Comment by Snorlax8** [comment]
@rasaffie: Es que nos sucedió algo curioso. Antes de que saliese el error, nosotros nunca agregamos al `Gemfile` la gema `rspec-rails`. Nos acabamos de dar cuenta de que en uno de los últimos _commits_ que hicimos, se agregó esa gema exclusivamente al `Gemfile.lock` y no al `Gemfile`. Entonces, para intentar que volviesen a estar en concordancia, agregamos manualmente la gema al `Gemfile` y volvimos a hacer `docker-compose build`. Luego, se subió este cambio en el `Gemfile` a git, pero nos sigue ocurriendo el problema.

**Comment by Zepk** [comment]
@rasaffie : Otra cosa que intentamos hacer, pensando que el problema estaba dado por una descordinacion entre el `Gemfile` y el `Gemfile.lock` fue el eliminar la gema `rspec-rails` (que agregamos originalmente para intentar solucionar este problema) del `Gemfile`. Luego de eso eliminamos el `Gemfile.lock` y corrimos `docker-compose build`. Esto hasta donde entiendo debiese crear un nuevo `Gemfile.lock` a partir de la informacion en `Gemfile`. 

Despues de hacer esto intentamos hacer deploy a Heroku nuevamente, sin embargo tenemos el siguiente error:
![screenshot from 2018-05-09 18-17-31](https://user-images.githubusercontent.com/11397612/39840430-c599e73e-53b5-11e8-90da-1d495c7fbe5a.png)

El cual segun entiendo dice que en algun lugar de nuestro codigo existe un error de sintaxis, sin embargo no he visto ninguno, y la aplicacion funciona de forma local, cosa que segun yo no debiese pasar si hubiese efectivamente un error de sintaxis.

**Comment by rasaffie** [comment]
¿Cuál es el _link_ exacto del _commit_ que quieren subir?

**Comment by Zepk** [comment]
El _commit_ en particular es [este](https://github.com/IIC2143-2018-1/grupo-03/commit/bab38cd4a7a143947452c0c719a867954eb35d5f)

**Comment by rasaffie** [comment]
Te recomiendo que a través de la herramienta de _Github_ para comparar cambios (https://github.com/IIC2143-2018-1/grupo-03/compare) veas qué cambios se hicieron entre ese _commit_ y el último que lograron subir a _Heroku_. 

En la pestaña _Activity_ de _Heroku_ puedes ver el _hash_ del último _commit_ con _deploy_ exitoso.

**Comment by rasaffie** [comment]
Pienso que con la actualización del `Gemfile.lock` solucionaron el primer error, y este segundo error se debe a algo diferente.

Revisando sus cambios veo algo muy extraño a partir de esta [línea](https://github.com/IIC2143-2018-1/grupo-03/compare/153b1f5...bab38cd#diff-b1fe55db50c712fef0673345e5b9c0d9R25): ¿cuál es la carpeta `Q` y por qué redefinen el `ApplicationHelper` en ese archivo?. Puede ser que a partir de eso se estén generando los problemas.

**Comment by rasaffie** [comment]
Por último, en este [_commit_](https://github.com/IIC2143-2018-1/grupo-03/commit/9ea56725a96b070859e67226aff78e3d6751b403) agregaron `rspec` al `Gemfile.lock` sin agregarlo al `Gemfile`.

**Comment by Snorlax8** [comment]
Gracias por todas las respuestas! 

Como grupo cometimos el error de realizar muchas funcionalidades sin hacer _deploy_ entremedio, por lo que resultaba muy difícil identificar en qué momento de nuestro desarrollo ocurrió algo que nos impedía hacer el _deploy_ y qué era ese algo. Por lo tanto, decidimos comenzar prácticamente desde cero, esta vez subiendo la app a Heroku cada vez que se completara un cambio suficientemente grande. Afortunadamente, no volvimos a encontrar un problema. 

Lección aprendida 🍰.
