### ISSUE TITLE
Docker crea "network" y la base de datos no aparece disponible para la aplicación

### ISSUE THREAD

**Issue by vixolo** [IIC2143-2018-1/project#47]
Estimados:

Luego de días de estar usando docker en mi Windows 10 Pro, y teniendo una aplicación que funcionaba bien (ingresando desde localhost sin problemas), hoy me metí y apareció un problema. Cuando intento conectarme a mi app, me aparece la pantalla roja de problema de rails diciendo 

> "FATAL: database "database_development" does not exist". 

Obviamente, fui e intenté con `docker-compose run web rails db:create` y `docker-compose run web rails db:migrate`. No funciona. He intentado prácticamente todo y oscilo entre que no me permite conectarme a localhost, y que me permita pero me aparezca ese error.

Otro dato es que cuando hago "docker-compose up" para iniciar los contenedores, me sale 

> Creating network "grupo-11_default" with the default driver
> Creating grupo-11_postgres_1 ... done
> Creating grupo-11_web_1      ... done
> Attaching to grupo-11_postgres_1, grupo-11_web_1

Lo cual NO solía salir, sino que salía:

> Starting grupo-11_postgres_1 ... done

etc...

Creo que ahí está la diferencia. El problema, es que no sé porqué empezó a crear una "network" cuando inicio el contenedor ni tampoco sé como hacer que deje de hacerlo. He buscado en internet acerca de redes, pero no logro encontrar como desactivarlo.

Muchísimas gracias por su ayuda,
Vicente.

**Comment by elramirezv** [comment]
Pudiste arregarlo? Me pasó lo mismo
