### ISSUE TITLE
No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by pitahorn** [IIC2143-2018-1/project#48]
Hola!
Docker me estaba arrojando problemas, así que volví a clonar el repositorio del proyecto. Cree el archivo .env sin problemas y docker-compose build también funcionó, pero al hacer docker-compose up arroja siempre el mismo error en consola:

```
web_1       | /grupo-07/Gemfile not found
web_1       |
web_1       | [!] There was an error parsing `Gemfile`: No such file or directory @ rb_sysopen - /grupo-07/Gemfile. Bundler cannot continue.
grupo-07_web_1 exited with code 4
```
Son los mismos archivos de antes y mi grupo no ha tenido este problema tampoco. He intentado todo, por favor ayuda :(

**Comment by LuisFros** [comment]
Si estas usando Windows, a mi me pasa lo mismo cuando empiezo docker desde cero. 
Segun lo que lei, esta relacionado con la conexion Hyper-V y el firewall de Windows.
El error significa que Docker no puede encontrar el Gemfile porque no se esta comprtiendo tu disco local correctamente. 
Siguiendo estos 2 links me resuelve el problema:

https://blog.olandese.nl/2017/05/03/solve-docker-for-windows-error-a-firewall-is-blocking-file-sharing-between-windows-and-the-containers/
- En este link, si vas a los ajustes del UI de Docker y tratas de comprtir tu disco local te debería aparecer lo que muestra el link. Si ese es el caso sigue las instrucciones para reinstalar el servicio .

https://stackoverflow.com/a/43904051
- Este es un comando que setea la conexion con docker para que sea accesible. Debes correrla con windows powershell como admin.


Espero que te sirva!

**Comment by LuisFros** [comment]
La otra posibilidad es que la variable de tu directorio, “$APP_HOME” en el archivo “dockercompose” no este seteada correctamente a tu directorio. Sigue el ejemplo del repositorio “ejemplo 1” si tienes dudas

**Comment by jiaranda** [comment]
Yo tuve el mismo problema en mac cuando instale todo con homebrew. Al final instalé  docker con el instalador que está en la página oficial y funciona todo perfecto (antes tienes que desinstalar todo con homebrew. brew uninstall ...)
