### ISSUE TITLE
Corrupted db

### ISSUE THREAD

**Issue by ofvera** [IIC2143-2018-1/project#49]
Estaba programando, cuando de la nada mi pc se apago (la batería esta mañosa). Al prenderlo nuevamente, docker empezó a fallar al realizar el compose up, donde dice lo siguiente:

``postgres_1  | 2018-05-11 22:09:40.656 UTC [20] LOG:  database system was shut down at 2018-05-11 22:04:03 UTC``
``postgres_1  | 2018-05-11 22:09:41.400 UTC [25] LOG:  corrupted statistics file "pg_stat/global.stat"``
``postgres_1  | 2018-05-11 22:09:41.578 UTC [1] LOG:  database system is ready to accept connections``

Leí que se debe a que se cerro abruptamente, pero no se donde ni como ver el problema en postgres.

**Comment by rasaffie** [comment]
Trata de borrar el contenedor de _postgres_ y vuelve a crearlo.
