### ISSUE TITLE
Error recurrente en sus repositorios

### ISSUE THREAD

**Issue by andresfdezc** [IIC2143-2018-1/project#5]
Hemos notado que varios grupos están creando una carpeta dentro de sus repositorios donde inicializan su aplicación Ruby on Rails. En consecuencia, sus repositorios se ven desde la raíz de la siguiente forma:

![screen shot 2018-03-18 at 8 45 11 pm](https://user-images.githubusercontent.com/11430184/37572710-da3da68a-2aed-11e8-81f4-8227b9a1f591.png)

El problema con esto es que RoR inicializa un repositorio de git también, por lo que esa carpeta (en este caso `app`) también es un repositorio de git en sí mismo. Los commits que se hagan ahí dentro NO se verán reflejados en el repositorio de GitHub desde donde les revisaremos.

Sus repositorios se deberían ver de la siguiente forma desde la raíz, para que estén seguros:

![screen shot 2018-03-18 at 8 42 54 pm](https://user-images.githubusercontent.com/11430184/37572721-10444cd4-2aee-11e8-9d0d-a78dab01a0ad.png)

**Comment by JoseValencia125** [comment]
Las historias de usuario se suben en una carpeta o al readme?

**Comment by andresfdezc** [comment]
@JoseValencia125 Se suben en la carpeta `relatos`, tal como sale en el enunciado de la entrega. Opcionalmente, pueden agregar el link de su Trello al readme con las tarjetas creadas.
Notar que esto último es además de invitar a su ayudante asignado a tal Trello, que es obligatorio según el enunciado de entrega.

**Comment by fdoflorenzano** [comment]
@JoseValencia125 notar la actualización del comentario anterior.
