### ISSUE TITLE
H10 - App crashed

### ISSUE THREAD

**Issue by movaldivia** [IIC2143-2018-1/project#51]
Hola,

Estoy intentado subir la aplicación a heroku pero me tira error H10 busqué por internet y nada.

![image](https://user-images.githubusercontent.com/24725124/39961381-350d9ff0-560b-11e8-9ff0-804524062f80.png)
![image](https://user-images.githubusercontent.com/24725124/39961394-610517e6-560b-11e8-984b-dbb0e4895729.png)

Debo decir que la aplicación funciona de forma perfecta en localhost.

No sé si alguien sabe como solucionarlo

**Comment by andresfdezc** [comment]
Tal vez esto sea muy tarde, pero el error real de la aplicación lo encontrarás más arriba en el log de heroku. Ese te indicará qué línea de qué archivo falló.

**Comment by rasaffie** [comment]
¿Revisaste los _logs_ de _Heroku_? Con el detalle que entregas es difícil saber la causa del error.
