### ISSUE TITLE
Error en localhost

### ISSUE THREAD

**Issue by acrojas2** [IIC2143-2018-1/project#53]
Hola! tengo un error :(
Pongo docker-compose start como siempre en mi terminal y luego voy al localhost:3000 y me aparece lo siguiente:
<img width="520" alt="captura de pantalla 2018-05-25 a la s 16 31 19" src="https://user-images.githubusercontent.com/26121354/40565143-597e7e8a-6039-11e8-9f70-4052c40951b9.png">
Alguien me puede ayudar con esto? Intenté a la mala y volvi crear el contenedor, pero no me funcionó y me sigue apareciendo esto. Nosé como googlear el error...
Espero que alguien me pueda ayudar :)
Gracias de antemano.

**Comment by andresfdezc** [comment]
Puedes ejecutar

`docker-compose logs --tail`

para ver el error que está haciendo que el programa se caiga. Con la información que nos das por ahora no podemos determinar mucho.

**Comment by acrojas2** [comment]
Creo que los errores comienzan desde acá:
<img width="1220" alt="captura de pantalla 2018-05-25 a la s 16 57 20" src="https://user-images.githubusercontent.com/26121354/40565999-c7710db0-603c-11e8-8afb-43a43d7146f7.png">
Nota: ejecuté docker-compose logs --tail= "all" por que con docker-compose logs --tail no me aparecía nada.

**Comment by acrojas2** [comment]
borre todos los contenedores para empezar de nuevo, pero creo que ahora todo esta peor :( ayudaa!

**Comment by acrojas2** [comment]
Como borre todos los contenedores, quize empezar de nuevo y comencé a seguir los pasos de la ayudantía cero, adjunto una imagen de esto:
<img width="724" alt="captura de pantalla 2018-05-25 a la s 17 44 31" src="https://user-images.githubusercontent.com/26121354/40567480-79e6dbcc-6043-11e8-9f0f-186abee6d647.png">
al seguir los pasos, me apareció este error:
<img width="725" alt="captura de pantalla 2018-05-25 a la s 17 44 43" src="https://user-images.githubusercontent.com/26121354/40567494-8cceb8c2-6043-11e8-9dc3-ad8fd8eb25c5.png">
Y no quiero seguir eliminando más cosas, pq parece que la embarro más! @andresfdezc puedes ayudarme a dejar todo como estaba 😢

**Comment by andresfdezc** [comment]
¿Cómo los borraste?

**Comment by andresfdezc** [comment]
Por favor muéstranos qué resulta de ejecutar `docker-compose ps` para ver el estado de los contenedores actuales, si los hay.

Por ahora te aviso que la forma estándar de eliminar los contenedores asociados a las imágenes de Docker que generamos en ayudantía es ejecutando `docker-compose down`. Después de eso basta ejecutar `docker-compose up -d` para crear nuevos controladores.

No intentes generar una nueva app de rails con `rails new ...` porque eso ha fue hecho y se ve reflejado en el código de tu grupo.

**Comment by acrojas2** [comment]
Acá va!
<img width="657" alt="captura de pantalla 2018-05-25 a la s 18 19 25" src="https://user-images.githubusercontent.com/26121354/40568372-40f94c00-6048-11e8-8580-43cad9acc41f.png">

**Comment by acrojas2** [comment]
docker stop $(docker ps -a -q) 
 docker rm $(docker ps -a -q) 
con esos comandos borre los contenedores 😢

**Comment by acrojas2** [comment]
¿Qué hago? Realmente no sé como solucionar mi problema, con cada solucion que intento lo dejo peor :(

**Comment by andresfdezc** [comment]
Esto no ha empeorado.

Los comandos que usaste no debieron haber hecho nada porque nosotros estamos usando docker-compose, no docker. Por favor muéstrame qué resulta de ejecutar `docker-compose down`.

**Comment by acrojas2** [comment]
Acá va:
<img width="564" alt="captura de pantalla 2018-05-25 a la s 18 34 01" src="https://user-images.githubusercontent.com/26121354/40568709-3f923f46-604a-11e8-9399-826c8026a8a6.png">
Una pregunta: cual es la diferencia entre usar docker y docker-compose?

**Comment by andresfdezc** [comment]
Por lo que se puede ver de lo que enviaste, se eliminaron los contenedores que tenías. Por favor ejecuta `docker-compose build` y `docker-compose up -d` para crear y encender contenedores nuevos.

Docker sirve para crear contenedores y se usa directamente si solo se necesita 1 contenedor. En nuestro caso usamos 2: uno para la aplicación en Rails y otro para la base de datos en Postgres. Docker Compose permite definir aplicaciones que usan más de un contenedor que interactúan entre ellos.

**Comment by acrojas2** [comment]
Acá va:
<img width="531" alt="captura de pantalla 2018-05-25 a la s 18 42 25" src="https://user-images.githubusercontent.com/26121354/40568887-744b9718-604b-11e8-824e-e25bfe04fa65.png">
todo bien...
<img width="515" alt="captura de pantalla 2018-05-25 a la s 18 43 13" src="https://user-images.githubusercontent.com/26121354/40568897-8173d3c4-604b-11e8-9f2e-b0155a9021f7.png">
Pero aún:
<img width="838" alt="captura de pantalla 2018-05-25 a la s 18 43 58" src="https://user-images.githubusercontent.com/26121354/40568915-9f762b2e-604b-11e8-909f-d768090d835d.png">
😢 😭

**Comment by andresfdezc** [comment]
Ejecuta `docker-compose logs` para ver el error. Probablemente sea uno nuevo y ya solucionamos el original.

**Comment by acrojas2** [comment]
Acá va:
<img width="1280" alt="captura de pantalla 2018-05-25 a la s 18 52 44" src="https://user-images.githubusercontent.com/26121354/40569104-e461b48c-604c-11e8-8bc6-2b1babeee01d.png">
<img width="1280" alt="captura de pantalla 2018-05-25 a la s 18 53 04" src="https://user-images.githubusercontent.com/26121354/40569111-f54bf3e8-604c-11e8-92e8-4fb62ca5ec8f.png">

**Comment by andresfdezc** [comment]
Borra el archivo `/grupo-18/tmp/pids/server.pid` y luego ejecuta `docker-compose restart`.

**Comment by andresfdezc** [comment]
(Como referencia, te recomendio leer esto después de que terminemos de solucionar todos los problemas: https://github.com/IIC2143-2018-1/project/issues/26#issuecomment-382934341)

**Comment by acrojas2** [comment]
Ahora me sale esto en el localhost:3000
<img width="1044" alt="captura de pantalla 2018-05-25 a la s 19 01 53" src="https://user-images.githubusercontent.com/26121354/40569261-27e96528-604e-11e8-9d8d-87f662e2c07b.png">

**Comment by andresfdezc** [comment]
Excelente, ya está todo funcionando como se espera.

Tendrás que crear la base de datos de nuevo (porque el contenedor de Postgres está nuevo) con:

`docker-compose exec web rails db:create`

y luego correr tus migraciones con:

`docker-compose exec web rails db:migrate`.

Después de esto debería quedar todo normal y funcionando.

**Comment by acrojas2** [comment]
Buenisimo! Todo volvió al orden 😄 
Muchisimas gracias!!!!!! Te pasaste y sorry, pero prefería preguntar a seguir mentiendo la pata :cold_sweat:
