### ISSUE TITLE
Form param is missing or the value is empty

### ISSUE THREAD

**Issue by movaldivia** [IIC2143-2018-1/project#55]
Hola

No puedo enviar de buena forma el post del form
![im1](https://user-images.githubusercontent.com/24725124/40870313-d8db2e1e-65fa-11e8-879b-46ec85858917.png)

Tras hacer submit me arroja el siguiente error:

![im2](https://user-images.githubusercontent.com/24725124/40870319-e82b75b8-65fa-11e8-9349-034e18a836e8.png)

Como pueden observar en los parametros no se está enviando el "objeto" permit, solo se están enviando los parámetros user y forum

He revisado en todas partes y no encuentro como solucionarlo

**Comment by rasaffie** [comment]
Debes usar `f.hidden_field` en vez de `hidden_field_tag` para que los parámetros queden asociados al objeto del formulario.
