### ISSUE TITLE
Mostrar post en vista del forum al que pertenece

### ISSUE THREAD

**Issue by acrojas2** [IIC2143-2018-1/project#56]
Hola:
Estoy trabajando en las vistas de mi proyecto y tengo el siguiente problema:
<img width="1015" alt="captura de pantalla 2018-06-11 a la s 20 33 09" src="https://user-images.githubusercontent.com/26121354/41263715-b6c7c206-6db6-11e8-8f92-73faf81334b7.png">
Me pasa exactamente lo mismo cuando quiero mostrar los comments en la vista del post al que pertenecen. Asi es que si me pueden ayudar, me ayudarían con dos problemas que estoy teniendo. He estado ene rato en esto, asi que por eso la issue.
Nota: tengo implementado lo del has_many y belongs_to.
Saludos

**Comment by andresfdezc** [comment]
El error que muestras está indicando que la variable `@forums` no está definida. Revisa que en el controlador estés asignando esa variable correctamente.

Por otra parte, ¿no querrás referirte a `@forum` (sin "s")? Asumo que estás intentando obtener los post de UN foro en particular y no de muchos.

**Comment by acrojas2** [comment]
Hola:
Ahora me salio este problema.
<img width="998" alt="captura de pantalla 2018-06-11 a la s 23 33 53" src="https://user-images.githubusercontent.com/26121354/41268853-0f56fc20-6dd0-11e8-859f-4c6c7000b205.png">
Que es básicamente el mismo, pero con la diferencia es que vuelvo a poner lo que estaba antes que sí funcionaba y no pasa nada :(.
Saludos.

**Comment by andresfdezc** [comment]
El problema no es lo mismo. ¿A qué te refieres con lo que estaba antes?

La función `new_forum_post_comments_path` se genera sola si es que existe una ruta con el prefijo `new_forum_post_comments_path`. Te sugiero revisar cuál es la ruta a la que quieres dirigir ese formulario y poner el helper de esa en url.

**Comment by acrojas2** [comment]
Me refiero a que vuelvo a poner lo que estaba en commits anteriores cuando funcionaba y eso ya no funciona. ¿A qué te refieres con lo del helper?

**Comment by acrojas2** [comment]
Perdón, era este el pantallazo y por eso me refería a que el error es basicamente el mismo al que habia indicado al princio. 
<img width="1050" alt="captura de pantalla 2018-06-12 a la s 08 20 27" src="https://user-images.githubusercontent.com/26121354/41290019-95741678-6e19-11e8-9771-a1c115ea3aa7.png">
Saludos!

**Comment by andresfdezc** [comment]
Esto ocurre porque alguna de las variables `@forum`, `@post` o `@comment` no fue asignada en el controlador. Como regla general, cuando aparezca `nil:NilClass` es porque una variable no fue asignada en el controlador o una función retornó vacío (por error o porque no encontró nada).

**Comment by acrojas2** [comment]
solucionado!
