### ISSUE TITLE
Error en Log In y muerte de Sign Up

### ISSUE THREAD

**Issue by acrojas2** [IIC2143-2018-1/project#57]
Hola!
Estoy arreglando el estilo de mi proyecto e hice modificaciones solo de divs y esas cosas, sin embargo ahora arruiné el Log In. Nosé porqué funciona vez por medio, literalmente vez por medio. El error que muestra es el siguiente:
<img width="1083" alt="captura de pantalla 2018-06-13 a la s 23 07 26" src="https://user-images.githubusercontent.com/26121354/41389388-98cd5618-6f5e-11e8-8756-aac09d5484c2.png">
Con respecto a Sign Up,  no me muestra ningún error pero no crea al nuevo usuario.
Si alguien puede ayudarme a descubrir que está pasando sería increible. Estos errores me han quitado ya muchas horas.  
(Ojala algún ayudante pueda revisar el repo de mi grupo {38})
Saludos.

**Comment by andresfdezc** [comment]
Como sugerencia general cuando se rompa algo que estaba funcionando antes, simplemente vuelve al commit anterior donde estaba funcionando.

**Comment by andresfdezc** [comment]
Sobre el error, devise agrega automáticamente dos inputs ocultos con tokens en html del formulario, como se puede ver a continuación.

![screen shot 2018-06-13 at 11 23 34 pm](https://user-images.githubusercontent.com/11430184/41389812-d8002ba6-6f60-11e8-9538-d08d22b7cdce.png)

Probablemente modificaste alguno de los métodos que devise usa para insertar esos inputs adicionales en la vista del login. Revisa que el tag con `form_for` esté correcto.

Si trabajaste en el layout de la aplicación, es puede que hayas borrado la línea 

```html
<%= csrf_meta_tags %>
```

Este es un error típico que aparece en varios links al googlear el error que muestras: https://stackoverflow.com/a/24081738.
