### ISSUE TITLE
No puedo hacer deploy: UndefinedTable: ERROR:  relation "forums_users" does not exist

### ISSUE THREAD

**Issue by BeaGaete** [IIC2143-2018-1/project#58]
Hola!! Cuando trato de hacer deploy me sale esto "_We're sorry, but something went wrong_". En heroku logs me sale lo siguiente: 
**[2018-06-16T02:48:10.482408 #4] FATAL -- : [45368b8a-789b-41d0-bfa6-c1c4d450e0d1] ActionView::Template::Error (PG::UndefinedTable: ERROR:  relation "forums_users" does not exist.**
Entonces lo que hice fue borrar el código de la tabla en el archivo schema (Había hecho antes otra tabla intermedia que cumple la misma función que "forums_users" pero con otro nombre, así que en realidad creo que "forums_users" no la estoy ocupando). Pero aún así me sigue saliendo ese error. Pleassssse, alguien me ayuda?

**Comment by rasaffie** [comment]
No se debe modificar directamente el contenido de `schema.rb` ya que se genera automáticamente una vez que se ejecutan las migraciones. Esto asegura consistencia entre las distintas bases de datos.

A partir del _log_ que compartiste puedo suponer que en alguna vista (por eso dice `ActionView`) estás invocando la relación entre `forums` y `users` (según las convenciones de _RoR_ la tabla `forums_users` debería usarse para eso) sin que la tabla exista en la base de datos.

Si estás usando otra tabla intermedia para esa relación debes especificarlo en el código, de lo contrario _RoR_ interpretará el código según las convenciones.

**Comment by rasaffie** [comment]
Ver https://github.com/IIC2143-2018-1/project/issues/70.
