### ISSUE TITLE
Horario Examen Sección 1

### ISSUE THREAD

**Issue by jiaranda** [IIC2143-2018-1/project#59]
Hola,

¿Alguien sabe el horario del examen de la sección 1? 🤔

**Comment by andresfdezc** [comment]
La hora exacta del examen todavía no ha sido determinada. Sólo te puedo confirmar por ahora que el examen será durante la mañana del jueves 28 de junio.

**Comment by rasaffie** [comment]
El horario asignado por la universidad es desde las 8:30 hasta las 12:50. De todas formas, tengo intención que el examen comience a las 9:00 y que no dure más de 2 horas. A comienzos de la próxima semana confirmaré el horario definitivo.
