### ISSUE TITLE
Plazo entrega

### ISSUE THREAD

**Issue by cilopez** [IIC2143-2018-1/project#60]
Si bien ya se ha preguntado antes, existe una posibilidad de aplazar la entrega para el domingo 24 a la misma hora.  Personalmente de todas formas trabajaría el domingo para tener las funcionalidades en la presentación por lo que quizás sería lo mismo en términos de avance pero no en términos de evaluación

**Comment by rasaffie** [comment]
La fecha de la entrega 4 no se aplazará.

Aprovecho de aclarar que la entrega 4 no es la entrega final: la entrega final corresponde al código que  esté en la _branch master_ al finalizar la última presentación del curso.
