### ISSUE TITLE
Properties en Rails

### ISSUE THREAD

**Issue by Okhan97** [IIC2143-2018-1/project#61]
Hola, me encuentro con un problema que san Google no me ha podido aclarar.

Para crear el sistema de reputacion del user se me ocurrió hacer una simple suma de todos los likes y dislikes que tienen sus comentarios y posts, entonces recordé que en avanzada para definir "atributos cambiantes" aplicabamos properties, que se recalculaban cada vez que uno los llamaba.

Sin embargo me está complicando el como implementar esto en rails, ¿¿debo crear un nuevo atributo con `rails generate migration AddNewColumnToMyTable column_name:column_type`
o debo crear un nuevo metodo en el controlador, o ambas ??.

¿Si agrego un nuevo atributo como hago para que este cambie cada vez que lo consulto ?

Y si solo debo agregar un metodo al controlador , ¿como puedo hacer que rails me retorne un int cuando lo llame de la manera user.reputation?

Quedo atento a la respuesta

**Comment by andresfdezc** [comment]
No necesitas crear una nueva migración, pues no es información que guardarás en la base de datos.

Como en Ruby los paréntesis de la ejecución de una función son opcionales, para crear algo que se comporte como property basta con añadir un método cualquiera al modelo. En tu caso, simplemente crea un método `reputation` en tu **modelo** (no controlador) `User`.

**Comment by Okhan97** [comment]
@andresfdezc  y para que luego en otros lados pueda llamar al metodo simplemente user.reputation, ¿cual de estas opciones debo usar? (rep es el valor que quiero que retorne).

self.reputation = rep
self[reputation] = rep 
user.reputation = rep 
return rep

**Comment by Okhan97** [comment]
Ya lo resolví, era con return ^^
Aunque solo por curiosidad, ¿las otras tiran error o igual podrian estar bien?

**Comment by andresfdezc** [comment]
1. `self.reputation = rep` no debiese resultar, porque estarías tratando de asignarle un valor a un método. Además, `self.reputation` debiese primero buscar un método de clase con ese nombre.
2. `self[reputation] = rep` buscaría en `self` algo con la key de lo que sea que retorne `reputation`, porque es un método.
3. `user.reputation = rep`, `user` no estaría definido dentro del método.
4. `return rep` es lo correcto, porque es un método y en algún momento tienes que retornar algún valor. De todas formas, recuerda que en Ruby las funciones retornan predeterminadamente lo último que se ejecute, por lo que si el `return` está en la última línea, éste se puede omitir.

Si necesitas acceder a `reputation` desde cualquier otro método del modelo, puedes llamarlo solo escribiendo `reputation`. No es necesario escribir `self.reputation` como en Python.
