### ISSUE TITLE
Duda de clases sobre mailer

### ISSUE THREAD

**Issue by elramirezv** [IIC2143-2018-1/project#62]
Hola!

Me encuentro haciendo lo de confirmar el sign in con el mail y me acordé que en clases, el profesor @rasaffie, mencionó que había una forma mas sencilla de visualizar los mails, que tener que enviarlo cada vez para probar. Cúal era? jajaja

Gracias!

**Comment by rasaffie** [comment]
En [esta sección](http://guides.rubyonrails.org/action_mailer_basics.html#previewing-emails) de la guía de _RoR_ puedes ver cómo se hace. Si estás usando _rspec_ la carpeta se llamará _spec_ en vez de _test_.
