### ISSUE TITLE
Error "535-5.7.8 Username and Password not accepted" con el mailer

### ISSUE THREAD

**Issue by elramirezv** [IIC2143-2018-1/project#63]
Hola!

Llevo un buen rato intentando hacer la confirmación de la cuenta con el mail, pero he tenido algunos problemas. Estoy usando el mailer de la gema 'devise', pero cuando intento ingresar me arroja el siguiente error: `Net::SMTPAuthenticationError in Devise::ConfirmationsController#create` especificamente `535-5.7.8 Username and Password not accepted`.

Verifiqué primero que lo que estaba haciendo mi programa estuviera correcto, y al parecer si lo está. La consola me muestra lo siguiente:

```
 Devise::Mailer#confirmation_instructions: processed outbound mail in 178.2ms
web_1       | Sent mail to elramirez@uc.cl (736.0ms)
web_1       | Date: Fri, 22 Jun 2018 23:17:11 +0000
web_1       | From: elramirezv123@gmail.com
web_1       | Reply-To: elramirezv123@gmail.com
web_1       | To: elramirez@uc.cl
web_1       | Message-ID: <5b2d837798fa7_12b0eb9bf0d9010022@df022e8da5fd.mail>
web_1       | Subject: Confirmation instructions
web_1       | Mime-Version: 1.0
web_1       | Content-Type: text/html;
web_1       |  charset=UTF-8
web_1       | Content-Transfer-Encoding: 7bit
web_1       | 
web_1       | <p>Welcome elramirez@uc.cl!</p>
web_1       | 
web_1       | <p>You can confirm your account email through the link below:</p>
web_1       | 
web_1       | <p><a href="http://localhost:3000/users/confirmation?confirmation_token=toqz7xiK3GzV8ysc_4VJ">Confirm my account</a></p>
web_1       | 
web_1       | Completed 500 Internal Server Error in 1086ms (ActiveRecord: 1.5ms)

```
Osea que el mail en teoría si se debería estar enviando, por lo que creo que Google es el que me está poniendo los problemas.
Para hacer la configuración, en el archivo `development.rb` setié lo siguiente:

```
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.default_url_options = { host:'localhost', port: '3000' }
  config.action_mailer.perform_deliveries = true
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.default :charset => "utf-8"
  config.action_mailer.smtp_settings = {
      :address => "smtp.gmail.com",
      :port => 587,
      :domain => 'localhost:3000',
      :user_name => "elramirezv123@gmail.com",
      :password => "micontraseña",
      :authentication => :plain
  }

```
Habilité la opción de que mi mail aceptara aplicaciones desconocidas y también cambié la contraseña de mi mail.
Por último, cada vez que pruebo la aplicación, reinicio el servidor.

Alguna idea de que puede ser :( ?

Muchas gracias!

**Comment by andresfdezc** [comment]
No creo que esto solucione tu problema, pero noto que te falta lo siguiente:
```
:enable_starttls_auto => true
```

Si es que no la has visto antes, en la siguiente issue de StackOverflow discuten distintas mañas del mailer con Gmail:

https://stackoverflow.com/questions/18124878/netsmtpauthenticationerror-when-sending-email-from-rails-app-on-staging-envir

**Comment by elramirezv** [comment]
Agregué la línea que me dijiste, cambié `:authentication => :plain` -> `:authentication => :login` y cambié la contraseña del mail de nuevo.

Y funcionó!

Gracias :DDDDD
