### ISSUE TITLE
Acceder a variables definidas en .env

### ISSUE THREAD

**Issue by cdlepe** [IIC2143-2018-1/project#64]
Hola! En ayudantía vimos que se podian definir varibles en el archivo .env para que fueran secretas, pero para acceder a ellas intento usar ENV["NOMBRE_VARIABLE"] y no funciona. Como puedo acceder a ellas desde cualquier parte del proyecto?

**Comment by andresfdezc** [comment]
Cuando cambias una variable de entorno es necesario volver a crear el
contenedor de Docker. Puedes hacer esto ejecutando `docker-compose up -d`.

La forma de acceder a ellas desde cualquier parte de la aplicación es como
dices. Puedes revisar que variables de entorno están efectivamente en tu
aplicación entrando a la consola de Rails con `docker-compose exec web
rails console` y ahí dentro revisar `ENV`.
