### ISSUE TITLE
Heroku security api credentials

### ISSUE THREAD

**Issue by ofvera** [IIC2143-2018-1/project#65]
Para que funcione la api, debía subir el archivo application.yml a heroku con las credenciales necesarias, sin embargo (lógicamente) me dice que es un riesgo de seguridad hacerlo. Tal como me dice heroku:

![image](https://user-images.githubusercontent.com/17597572/41813801-c2b75902-770a-11e8-89d7-3236e6e89b74.png)

Me recomienda editar lo siguiente ubicado en config/production.rb:
config.assets.compile = false # Disables security vulnerability

Sin embargo esto no soluciona el problema mismo, ya que ahora que realice ese cambio no tengo acceso a ningún asset de la página (incluida la api). Como podría manejar este error?

**Comment by andresfdezc** [comment]
El log tambien sugiere actualizar sprockets a la versión 3.7.2. Pueden hacerlo directamente en el Gemfile. ¿Intentaron eso?

**Comment by andresfdezc** [comment]
Otra alternativa es reemplazar todas las keys que tengan en el archivo `application.yml` por variables de entorno.

Por ejemplo
```
AWS_ACCESS_KEY_ID: 'KEYCOMPLETAMENTEEXPUESTA'
```

se puede reemplazar por
```
AWS_ACCESS_KEY_ID: <%= ENV["AWS_ACCESS_KEY_ID"] %>
```

siempre y cuando la variable de entorno `AWS_ACCESS_KEY_ID ` esté seteada.

Pueden ver un ejemplo de esto en su archivo `config/database.yml`.

**Comment by ofvera** [comment]
Usamos las keys y funciona la API, pero seguía molestando a los assets (imagenes), así que las guardamos en amazon web service 3 para verlas desde ahí.

Gracias!
