### ISSUE TITLE
Error al hacer docker-compose 

### ISSUE THREAD

**Issue by elramirezv** [IIC2143-2018-1/project#7]
Hola,

Estaba tratando de iniciar una app de prueba en Docker. Instalé todo y seguí los pasos de la ayudantía pero cuando escribí el comando `docker-compose build` me tirá el siguiente error:
```
postgres uses an image, skipping
Building web
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

```

Nose si me salté algún paso o algo. Estuve buscando en internet pero no entendí muy bien jajaja
PD: Ocupo Ubuntu e hice esto desde la terminal

Gracias!

**Comment by elramirezv** [comment]
Ya caché que era!

**Comment by rasaffie** [comment]
¿Y qué era?

**Comment by elramirezv** [comment]
Lo pude solucionar de 2 formas:

La primera fue siguiendo los pasos del siguiente link: 
https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user

Creando el `docker` group y luego agregando el usuario:
```
$ sudo groupadd docker
$ sudo usermod -aG docker $USER
```
El problema de esto es que tengo que hacerlo cada vez que inicio sesión en la terminal (nose porqué)

La otra forma más sencilla, es colocando `sudo` antes de cada comando de `docker-compose`
```
$ sudo docker-compose build
```
