### ISSUE TITLE
Fecha notas examen

### ISSUE THREAD

**Issue by fguinez** [IIC2143-2018-1/project#71]
Hola! ¿Hay alguna fecha aproximada definida en la que se entregarán las notas de los exámenes? (no pregunto para presionar, solo tengo la duda)

**Comment by andresfdezc** [comment]
Para la sección 1 (de Rodrigo Saffie) (la tuya) esperamos tener las notas listas durante el lunes.

**Comment by fguinez** [comment]
Gracias! tengo una última duda con respecto a eso: ¿Habrá instancia de recorreción? Y de ser así, ¿puede recorregir otra persona por mí en caso de que no esté en Santiago?

**Comment by rasaffie** [comment]
Sí a ambas preguntas. Lo más probable es que esa instancia sea durante el lunes o martes de la próxima semana.
