### ISSUE TITLE
Permission denied al editar archivos en Linux

### ISSUE THREAD

**Issue by elramirezv** [IIC2143-2018-1/project#9]
Hola!

Estuve siguiendo los pasos de la ayudantía para crear la app en mi pc. El problema es que cuando llego al paso de editar el archivo `config/database.yml`, lo abro en Atom pero cuando lo intento guardar me aparece esto:
![screenshot from 2018-03-21 20 40 30](https://user-images.githubusercontent.com/22776270/37743462-f20a8a32-2d48-11e8-949d-8c244e4cc0c4.png)

Lo extraño esque cuando creo la app utilizando solamente rails (Sin los comandos de docker) no me pasa esto. Alguien sabe qué puede ser? O bien algún comando para poder sacar lo de los permisos?

PD: utilizo Ubuntu

Gracias!

**Comment by andresfdezc** [comment]
Docker requiere un paso adicional, para los que están usando Linux, antes de hacer `docker-compose build`. Este paso añade los permisos al usuario actual para que los archivos del contenedor no sean solo de `root`.

https://docs.docker.com/compose/rails/#build-the-project

>If you are running Docker on Linux, the files rails new created are owned by root. This happens because the container runs as the root user. If this is the case, change the ownership of the new files.
>```bash
>sudo chown -R $USER:$USER .
>```

**Comment by elramirezv** [comment]
Ahora si funcionó! Gracias :+1:  :+1:  :+1:  :+1:

**Comment by andresfdezc** [comment]
Voy a dejar la issue abierta un rato porque esto es importante.
